/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as NewsRouteImport } from './routes/news'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as TestimonialsRouteRouteImport } from './routes/testimonials/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestimonialsIndexRouteImport } from './routes/testimonials/index'
import { Route as TestimonialsSlugRouteImport } from './routes/testimonials/$slug'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRouteRoute = TestimonialsRouteRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsIndexRoute = TestimonialsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestimonialsRouteRoute,
} as any)
const TestimonialsSlugRoute = TestimonialsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TestimonialsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/testimonials': typeof TestimonialsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/testimonials/$slug': typeof TestimonialsSlugRoute
  '/testimonials/': typeof TestimonialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/testimonials/$slug': typeof TestimonialsSlugRoute
  '/testimonials': typeof TestimonialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/testimonials': typeof TestimonialsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/testimonials/$slug': typeof TestimonialsSlugRoute
  '/testimonials/': typeof TestimonialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/testimonials'
    | '/about'
    | '/book'
    | '/news'
    | '/services'
    | '/testimonials/$slug'
    | '/testimonials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/news'
    | '/services'
    | '/testimonials/$slug'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/testimonials'
    | '/about'
    | '/book'
    | '/news'
    | '/services'
    | '/testimonials/$slug'
    | '/testimonials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestimonialsRouteRoute: typeof TestimonialsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  NewsRoute: typeof NewsRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/': {
      id: '/testimonials/'
      path: '/'
      fullPath: '/testimonials/'
      preLoaderRoute: typeof TestimonialsIndexRouteImport
      parentRoute: typeof TestimonialsRouteRoute
    }
    '/testimonials/$slug': {
      id: '/testimonials/$slug'
      path: '/$slug'
      fullPath: '/testimonials/$slug'
      preLoaderRoute: typeof TestimonialsSlugRouteImport
      parentRoute: typeof TestimonialsRouteRoute
    }
  }
}

interface TestimonialsRouteRouteChildren {
  TestimonialsSlugRoute: typeof TestimonialsSlugRoute
  TestimonialsIndexRoute: typeof TestimonialsIndexRoute
}

const TestimonialsRouteRouteChildren: TestimonialsRouteRouteChildren = {
  TestimonialsSlugRoute: TestimonialsSlugRoute,
  TestimonialsIndexRoute: TestimonialsIndexRoute,
}

const TestimonialsRouteRouteWithChildren =
  TestimonialsRouteRoute._addFileChildren(TestimonialsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestimonialsRouteRoute: TestimonialsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  NewsRoute: NewsRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
